patch for gcc4.8-issue ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 ): hnat_nf_hook.c:31:9: error: missing braces around initializer
compiles now fine (changed in readme), tests needed